title: Philip Lambok's Slice of Life
author: Philip Lambok
url: https://philiplambok.github.io
avatar_url: /assets/images/avatar.jpg
paginate: 5
paginate_path: /page:num/

collections:
  books:
    output: true
  works: 
    output: true
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _scss
  style: :compressed
plugins: [jekyll-paginate]